// <auto-generated />
using System;
using CookBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookBot.Infrastructure.Migrations
{
    [DbContext(typeof(CookBotDbContext))]
    [Migration("20260608030954_AddNutritionTables")]
    partial class AddNutritionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CookBot.Domain.Entities.AiApiKeyShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("OwnerUserId", "RecipientUserId")
                        .IsUnique();

                    b.ToTable("AiApiKeyShares");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.AiConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AiConversations");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.AiUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetryAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("KeyOwnerId", "Timestamp")
                        .HasDatabaseName("IX_AiUsageLogs_KeyOwnerId_Timestamp");

                    b.ToTable("AiUsageLogs");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.CnfConversionFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConversionFactorValue")
                        .HasColumnType("REAL");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeasureDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("CnfConversionFactors");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.CnfFood", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CarbGPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyKcalPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("FatGPer100g")
                        .HasColumnType("REAL");

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodGroup")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedDescription")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinGPer100g")
                        .HasColumnType("REAL");

                    b.HasKey("FoodId");

                    b.HasIndex("NormalizedDescription");

                    b.ToTable("CnfFoods");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Cookbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cookbooks");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.CookbookShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookbookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedWithUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SharedWithUserId");

                    b.HasIndex("CookbookId", "SharedWithUserId")
                        .IsUnique();

                    b.ToTable("CookbookShares");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.GroceryList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.GroceryListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("GroceryListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroceryListId");

                    b.HasIndex("IngredientId");

                    b.ToTable("GroceryListItems");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NutritionalInfoJson")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredUnitsJson")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Pantry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pantries");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.PantryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PantryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("PantryId", "IngredientId")
                        .IsUnique();

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.PantryMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PantryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PantryId", "UserId")
                        .IsUnique();

                    b.ToTable("PantryMembers");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalDocumentJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookbookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CookbookId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeLocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId", "IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipeMade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "CompletedAt");

                    b.HasIndex("UserId", "CompletedAt");

                    b.ToTable("RecipeMades");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipeNutritionCache", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalDocHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchedIngredients")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerIngredientMatchJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PerServingCarbG")
                        .HasColumnType("REAL");

                    b.Property<double>("PerServingEnergyKcal")
                        .HasColumnType("REAL");

                    b.Property<double>("PerServingFatG")
                        .HasColumnType("REAL");

                    b.Property<double>("PerServingProteinG")
                        .HasColumnType("REAL");

                    b.Property<int?>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalCarbG")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalEnergyKcal")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalFatG")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalIngredients")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalProteinG")
                        .HasColumnType("REAL");

                    b.HasKey("RecipeId");

                    b.ToTable("RecipeNutritionCaches");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("RecipePhotos");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Name")
                        .IsUnique();

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.ScheduledRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "ScheduledFor");

                    b.ToTable("ScheduledRecipes");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCookBotAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiApiKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("AiModel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AiSharedKeyOwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiSystemPromptTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiUnitExceptions")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DietaryPreferencesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitchenToolsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiSharedKeyOwnerUserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.AiApiKeyShare", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.User", "Owner")
                        .WithMany("AiApiKeySharesOwned")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.User", "Recipient")
                        .WithMany("AiApiKeySharesReceived")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.AiConversation", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.User", "User")
                        .WithMany("AiConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.AiUsageLog", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.User", "KeyOwner")
                        .WithMany()
                        .HasForeignKey("KeyOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyOwner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.CnfConversionFactor", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.CnfFood", "Food")
                        .WithMany("ConversionFactors")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Cookbook", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.User", "User")
                        .WithMany("Cookbooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.CookbookShare", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Cookbook", "Cookbook")
                        .WithMany("Shares")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.User", "SharedWithUser")
                        .WithMany()
                        .HasForeignKey("SharedWithUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cookbook");

                    b.Navigation("SharedWithUser");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.GroceryList", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.User", "User")
                        .WithMany("GroceryLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.GroceryListItem", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.GroceryList", "GroceryList")
                        .WithMany("Items")
                        .HasForeignKey("GroceryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroceryList");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Pantry", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.User", "Owner")
                        .WithMany("OwnedPantries")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.PantryItem", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("PantryItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.Pantry", "Pantry")
                        .WithMany("Items")
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Pantry");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.PantryMember", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Pantry", "Pantry")
                        .WithMany("Members")
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.User", "User")
                        .WithMany("PantryMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pantry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Cookbook", "Cookbook")
                        .WithMany("Recipes")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("CookBot.Domain.Entities.RecipeStep", "Steps", b1 =>
                        {
                            b1.Property<int>("RecipeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.PrimitiveCollection<string>("IngredientRefs")
                                .IsRequired();

                            b1.Property<bool>("IsSection");

                            b1.Property<int>("Order");

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.HasKey("RecipeId", "__synthesizedOrdinal");

                            b1.ToTable("Recipes");

                            b1
                                .ToJson("Steps")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.OwnsMany("CookBot.Domain.Entities.StepTimer", "Timers", b2 =>
                                {
                                    b2.Property<int>("RecipeStepRecipeId");

                                    b2.Property<int>("RecipeStep__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<int>("Duration");

                                    b2.Property<string>("Label");

                                    b2.Property<string>("Unit")
                                        .IsRequired();

                                    b2.HasKey("RecipeStepRecipeId", "RecipeStep__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Recipes");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeStepRecipeId", "RecipeStep__synthesizedOrdinal");
                                });

                            b1.Navigation("Timers");
                        });

                    b.Navigation("Cookbook");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipeMade", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipeNutritionCache", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Recipe", "Recipe")
                        .WithOne()
                        .HasForeignKey("CookBot.Domain.Entities.RecipeNutritionCache", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipePhoto", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Photos")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.RecipeTag", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.ScheduledRecipe", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("CookBot.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AiSharedKeyOwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CookBot.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("CookBot.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.CnfFood", b =>
                {
                    b.Navigation("ConversionFactors");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Cookbook", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.GroceryList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("PantryItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Pantry", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("CookBot.Domain.Entities.User", b =>
                {
                    b.Navigation("AiApiKeySharesOwned");

                    b.Navigation("AiApiKeySharesReceived");

                    b.Navigation("AiConversations");

                    b.Navigation("Cookbooks");

                    b.Navigation("GroceryLists");

                    b.Navigation("OwnedPantries");

                    b.Navigation("PantryMemberships");

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
