using CookBot.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CookBot.Infrastructure.Data.Configurations;

/// <summary>
/// EF fluent configuration for <see cref="CnfFood"/> (NUTR-01 / Phase 15 / Plan 15-03).
/// Discovered automatically by ApplyConfigurationsFromAssembly — no change to CookBotDbContext.cs needed.
/// FoodId is the CNF FoodCode (externally assigned) — ValueGeneratedNever preserves the CNF code.
/// </summary>
public class CnfFoodConfiguration : IEntityTypeConfiguration<CnfFood>
{
    public void Configure(EntityTypeBuilder<CnfFood> builder)
    {
        builder.HasKey(f => f.FoodId);
        // FoodId is the CNF FoodCode — assigned by the seed, NOT auto-generated by EF.
        builder.Property(f => f.FoodId).ValueGeneratedNever();

        builder.Property(f => f.FoodDescription).HasMaxLength(300).IsRequired();
        builder.Property(f => f.NormalizedDescription).HasMaxLength(300);
        builder.Property(f => f.FoodGroup).HasMaxLength(100);

        // Index for name-matching queries (runtime CNF lookup path)
        builder.HasIndex(f => f.NormalizedDescription);

        // Cascade: deleting a CnfFood removes all its ConversionFactor children
        builder.HasMany(f => f.ConversionFactors)
            .WithOne(cf => cf.Food)
            .HasForeignKey(cf => cf.FoodId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
