using CookBot.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CookBot.Infrastructure.Data.Configurations;

/// <summary>
/// EF fluent configuration for <see cref="RecipeNutritionCache"/> (NUTR-01 / Phase 15 / Plan 15-03).
/// Discovered automatically by ApplyConfigurationsFromAssembly — no change to CookBotDbContext.cs needed.
/// 1:1 cascade FK to Recipe — deleting a Recipe drops its nutrition cache automatically.
/// </summary>
public class RecipeNutritionCacheConfiguration : IEntityTypeConfiguration<RecipeNutritionCache>
{
    public void Configure(EntityTypeBuilder<RecipeNutritionCache> builder)
    {
        builder.HasKey(c => c.RecipeId);
        // RecipeId equals the Recipe PK — not auto-generated by EF.
        builder.Property(c => c.RecipeId).ValueGeneratedNever();

        // TEXT for the per-ingredient match JSON (mirrors Recipe.CanonicalDocumentJson — RecipeConfiguration.cs)
        builder.Property(c => c.PerIngredientMatchJson).HasColumnType("TEXT");

        // SHA-256 hex digest = 64 characters
        builder.Property(c => c.CanonicalDocHash).HasMaxLength(64).IsRequired();

        // WR-04: Concurrency token — refreshed on every write.
        // IsConcurrencyToken() tells EF to include RowVersion in WHERE clauses on UPDATE,
        // so a concurrent write on a different DbContext instance will throw
        // DbUpdateConcurrencyException rather than silently clobbering the other write.
        // Using Guid (TEXT column) because SQLite has no native row-version/xmin type.
        builder.Property(c => c.RowVersion)
            .IsConcurrencyToken()
            .HasColumnType("TEXT");

        // 1:1 cascade — deleting the Recipe removes the cache row
        builder.HasOne(c => c.Recipe)
            .WithOne()
            .HasForeignKey<RecipeNutritionCache>(c => c.RecipeId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
