using System.Text;
using CookBot.Application.Services;
using CookBot.Domain.Recipes;

namespace CookBot.Application.Recipes;

/// <summary>
/// Pure, stateless projector from a canonical <see cref="RecipeDocument"/> to a Cooklang
/// <c>.cook</c> string (one-way export — INTEROP-03 / INTEROP-04).
///
/// <para>Cooklang has NO escape character. All user-derived text is sanitized before emission
/// (D7 / INTEROP-04):
/// <list type="bullet">
///   <item>Step prose: token sigils <c>@ # ~</c>, brace delimiters <c>{ } %</c>, embedded
///     newlines (collapsed to a space), and line-leading structural markers <c>-- >> ==</c>
///     are all neutralized so prose stays a single logical line.</item>
///   <item>Ingredient names/units, timer labels/units, section headings, and equipment items:
///     brace/percent chars <c>{ } %</c>, token sigils <c>@ # ~</c>, and embedded newlines are
///     stripped/collapsed. These appear inside or as delimiters of Cooklang tokens, so the
///     token sigils themselves (<c>@</c> prefix, <c>== … ==</c> delimiters) are always
///     generated by the projector, never from user text.</item>
/// </list>
/// Ingredient tokens always use the braces form <c>@name{amount%unit}</c> so multi-word and
/// punctuated names are never truncated (§Pitfall 3). Recipe-level equipment is emitted as
/// metadata/comment lines, never as inline <c>#cookware</c> (D8). Substitutions come
/// exclusively from <see cref="IngredientEntry.Substitutions"/> and are grouped in a single
/// trailing comment block at the end of the output.</para>
/// </summary>
public static class CooklangRecipeProjector
{
    /// <summary>
    /// Projects <paramref name="doc"/> to a Cooklang <c>.cook</c> string.
    /// </summary>
    /// <param name="doc">The canonical recipe document (v4).</param>
    /// <returns>The full Cooklang text ready to be written to a <c>.cook</c> file.</returns>
    public static string Project(RecipeDocument doc)
    {
        var sb = new StringBuilder();

        // ── Metadata (>> key: value) ────────────────────────────────────────────────
        sb.Append(">> servings: ").Append(doc.Servings).Append('\n');

        if (doc.PrepTimeMinutes is { } prep && prep > 0)
            sb.Append(">> prep time: ").Append(prep).Append(" min\n");

        if (doc.CookTimeMinutes is { } cook && cook > 0)
            sb.Append(">> cook time: ").Append(cook).Append(" min\n");

        if (doc.Provenance is { } prov)
        {
            var parts = new List<string>(3);
            if (!string.IsNullOrWhiteSpace(prov.SourceName))   parts.Add(prov.SourceName);
            if (!string.IsNullOrWhiteSpace(prov.AuthorName))   parts.Add(prov.AuthorName);
            if (!string.IsNullOrWhiteSpace(prov.SourceUrl))    parts.Add(prov.SourceUrl);
            if (parts.Count > 0)
                sb.Append(">> source: ").Append(string.Join(", ", parts)).Append('\n');
        }

        // ── Equipment (recipe-level → -- comment lines; NOT inline #cookware) ──────
        foreach (var item in doc.Equipment)
        {
            if (!string.IsNullOrWhiteSpace(item))
                sb.Append("-- Equipment: ").Append(SanitizeToken(item)).Append('\n');
        }

        if (doc.Equipment.Count > 0)
            sb.Append('\n');

        // ── Steps ───────────────────────────────────────────────────────────────────
        foreach (var step in doc.Steps)
        {
            switch (step)
            {
                case SectionStep s:
                    sb.Append("== ").Append(SanitizeToken(s.Heading)).Append(" ==\n");
                    break;

                case ContentStep c:
                    // Strip [name](#id) links to their visible label, then sanitize Cooklang
                    // special chars from prose — Cooklang has NO escape character.
                    var prose = Sanitize(RecipeStepTextFormatter.ToPlainText(c.Text));

                    // Append structured timer tokens inline after the prose.
                    if (c.Timers is { Count: > 0 } timers)
                    {
                        var timerParts = new StringBuilder();
                        foreach (var t in timers)
                        {
                            timerParts.Append(' ');
                            var timerUnit = SanitizeToken(t.Unit);
                            if (!string.IsNullOrEmpty(t.Label))
                                timerParts.Append('~').Append(SanitizeToken(t.Label)).Append('{').Append(t.Duration).Append('%').Append(timerUnit).Append('}');
                            else
                                timerParts.Append('~').Append('{').Append(t.Duration).Append('%').Append(timerUnit).Append('}');
                        }
                        sb.Append(prose).Append(timerParts).Append('\n');
                    }
                    else
                    {
                        sb.Append(prose).Append('\n');
                    }

                    // Per-step temperature → -- comment
                    if (c.Temperature is { } temp)
                    {
                        var unitSymbol = temp.Unit switch
                        {
                            TemperatureUnit.F   => "°F",
                            TemperatureUnit.C   => "°C",
                            TemperatureUnit.Gas => "Gas Mark",
                            _                   => temp.Unit.ToString(),
                        };
                        sb.Append("-- ").Append(temp.Value).Append(unitSymbol).Append('\n');
                    }

                    // Doneness cue → -- comment
                    if (!string.IsNullOrEmpty(c.DonenessCue))
                        sb.Append("-- ").Append(c.DonenessCue).Append('\n');

                    break;
            }
        }

        if (doc.Steps.Count > 0)
            sb.Append('\n');

        // ── Ingredients section (ALWAYS braces form — §Pitfall 3 / D7) ──────────────
        foreach (var ing in doc.Ingredients)
        {
            // @name{amount%unit} | @name{amount} | @name{}
            // Sanitize name/unit: { } % @ # ~ and newlines must not break the token.
            sb.Append('@').Append(SanitizeToken(ing.Name)).Append('{');
            if (ing.Amount > 0 || !string.IsNullOrEmpty(ing.Unit))
            {
                sb.Append(FractionFormatter.Format(ing.Amount));
                if (!string.IsNullOrEmpty(ing.Unit))
                    sb.Append('%').Append(SanitizeToken(ing.Unit));
            }
            sb.Append('}').Append('\n');
        }

        // ── Trailing substitution comment block (sourced ONLY from IngredientEntry.Substitutions)
        // Deterministic order: doc.Ingredients in order, then each ingredient's Substitutions in order.
        var hasSubs = false;
        foreach (var ing in doc.Ingredients)
        {
            if (ing.Substitutions.Count == 0) continue;
            if (!hasSubs)
            {
                sb.Append('\n');
                hasSubs = true;
            }
            foreach (var sub in ing.Substitutions)
                sb.Append("-- Substitution (").Append(SanitizeToken(ing.Name)).Append("): ").Append(SanitizeToken(sub.Note)).Append('\n');
        }

        return sb.ToString();
    }

    /// <summary>
    /// Grammar-complete sanitizer for step prose (WR-01 / WR-02 / INTEROP-04).
    /// Cooklang has NO escape character; all grammar-significant characters must be
    /// neutralized before free-form text reaches the <c>.cook</c> output.
    ///
    /// <para>Handles:
    /// <list type="bullet">
    ///   <item>Embedded newlines — collapsed to a space so prose stays a single logical line.</item>
    ///   <item>Token sigils <c>@ # ~</c> — stripped (would create spurious ingredient/cookware/timer tokens).</item>
    ///   <item>Brace/percent delimiters <c>{ } %</c> — stripped (would break token interiors).</item>
    ///   <item>Line-leading structural markers <c>-- >> ==</c> — each double char reduced to single
    ///     so the output never starts a comment, metadata, or section-heading line.</item>
    /// </list>
    /// </para>
    /// </summary>
    private static string Sanitize(string prose)
    {
        // 1. Collapse embedded newlines first so prose stays a single logical line.
        prose = prose.Replace("\r\n", " ", StringComparison.Ordinal)
                     .Replace('\n', ' ')
                     .Replace('\r', ' ');
        // 2. Strip inline token sigils — would create spurious @ingredient/#cookware/~timer tokens.
        prose = prose.Replace("@", "", StringComparison.Ordinal)
                     .Replace("#", "", StringComparison.Ordinal)
                     .Replace("~", "", StringComparison.Ordinal);
        // 3. Strip brace/percent chars — would break @name{amount%unit} token interiors.
        prose = prose.Replace("{", "", StringComparison.Ordinal)
                     .Replace("}", "", StringComparison.Ordinal)
                     .Replace("%", "", StringComparison.Ordinal);
        // 4. Neutralize line-leading structural markers wherever they appear in the string.
        //    A prose string starting with "--" becomes a Cooklang comment line; ">> " becomes
        //    metadata; "==" becomes a section heading. Collapse each doubled char to single.
        prose = prose.Replace("--", "-", StringComparison.Ordinal)
                     .Replace(">>", ">", StringComparison.Ordinal)
                     .Replace("==", "=", StringComparison.Ordinal);
        return prose.Trim();
    }

    /// <summary>
    /// Sanitizer for token-interior fields: ingredient names/units, timer labels/units,
    /// section headings, equipment items, and substitution notes (WR-02 / INTEROP-04).
    ///
    /// <para>These fields appear inside Cooklang token delimiters (<c>{ }</c>, <c>== ==</c>,
    /// <c>-- </c>) generated by the projector itself. The projector-emitted delimiters are
    /// already correct; this sanitizer ensures the field content cannot prematurely close or
    /// corrupt them by stripping <c>{ } %</c> (token delimiters), <c>@ # ~</c> (sigils that
    /// could create nested tokens), and collapsing embedded newlines.</para>
    /// </summary>
    private static string SanitizeToken(string? value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;
        // Collapse newlines — a multi-line value would inject extra lines into the output.
        var s = value.Replace("\r\n", " ", StringComparison.Ordinal)
                     .Replace('\n', ' ')
                     .Replace('\r', ' ');
        // Strip chars that break token delimiters: { closes the braces token; % adds a
        // spurious amount/unit separator; @ # ~ would create nested ingredient/cookware/timer.
        s = s.Replace("{", "", StringComparison.Ordinal)
             .Replace("}", "", StringComparison.Ordinal)
             .Replace("%", "", StringComparison.Ordinal)
             .Replace("@", "", StringComparison.Ordinal)
             .Replace("#", "", StringComparison.Ordinal)
             .Replace("~", "", StringComparison.Ordinal);
        // Neutralize structural markers — a section heading or equipment item containing
        // "--" / ">>" / "==" could inject spurious grammar when the value appears in
        // a "== ... ==" heading or "-- ..." comment context.
        s = s.Replace("--", "-", StringComparison.Ordinal)
             .Replace(">>", ">", StringComparison.Ordinal)
             .Replace("==", "=", StringComparison.Ordinal);
        return s.Trim();
    }
}
